---
Name: toastseo
After:
  - 'siteconfig/*'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - ToastNZ\SEO\Extensions\ToastSEO

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - ToastNZ\SEO\Extensions\ToastSEOSiteConfigExtension
